@props([
    'title' => '',
    'description' => '',
    'createButtonText' => 'Create',
    'createButtonRoute' => '#',
    'searchPlaceholder' => 'Search...',
    'columns' => [],
    'data' => [],
    'rowsPerPage' => null
])

@php
    // Use items_per_page setting if rowsPerPage is not provided
    $rowsPerPage = $rowsPerPage ?? items_per_page();
@endphp

<div class="content-header">
    <div class="content-header-left">
        <h3>{{ $title }}</h3>
        @if($description)
        <p class="content-description">{{ $description }}</p>
        @endif
    </div>
    @if($createButtonText)
    <button class="btn btn-primary" onclick="window.location='{{ $createButtonRoute }}'">
        <span class="material-symbols-outlined">add</span>
        {{ $createButtonText }}
    </button>
    @endif
</div>

<div class="search-section">
    <div class="search-group">
        <input type="text" class="search-input" placeholder="{{ $searchPlaceholder }}" id="table-search">
        <button class="btn btn-reset" id="table-reset">RESET</button>
    </div>
</div>

<div class="table-container">
    <table class="data-table">
        <thead>
            <tr>
                @foreach($columns as $column)
                <th>{{ $column }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody id="table-body">
            {{ $slot }}
        </tbody>
    </table>
</div>

<div class="table-footer">
    <div class="showing-info" id="showing-info">
        Showing 1 to {{ count($data) }} of {{ count($data) }} entries
    </div>
    <div class="pagination" id="pagination-container">
        <!-- Pagination will be generated by JavaScript -->
    </div>
</div>

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    const searchInput = document.getElementById('table-search');
    const resetBtn = document.getElementById('table-reset');
    const tableRows = document.querySelectorAll('#table-body tr');
    const paginationContainer = document.getElementById('pagination-container');
    const rowsPerPage = {{ $rowsPerPage }};
    let currentPage = 1;
    let filteredRows = Array.from(tableRows);
    
    // Search functionality
    searchInput.addEventListener('keyup', function() {
        const searchTerm = this.value.toLowerCase();
        
        filteredRows = Array.from(tableRows).filter(row => {
            const text = row.textContent.toLowerCase();
            return text.includes(searchTerm);
        });
        
        currentPage = 1;
        displayPage(currentPage);
        renderPagination();
    });
    
    // Reset functionality
    resetBtn.addEventListener('click', function() {
        searchInput.value = '';
        filteredRows = Array.from(tableRows);
        currentPage = 1;
        displayPage(currentPage);
        renderPagination();
    });
    
    // Display page
    function displayPage(page) {
        const start = (page - 1) * rowsPerPage;
        const end = start + rowsPerPage;
        
        tableRows.forEach(row => row.style.display = 'none');
        
        filteredRows.slice(start, end).forEach(row => {
            row.style.display = '';
        });
        
        updateShowingInfo();
    }
    
    // Get total pages
    function getTotalPages() {
        return Math.ceil(filteredRows.length / rowsPerPage);
    }
    
    // Update showing info
    function updateShowingInfo() {
        const showingInfo = document.getElementById('showing-info');
        const total = filteredRows.length;
        const start = (currentPage - 1) * rowsPerPage + 1;
        const end = Math.min(currentPage * rowsPerPage, total);
        
        if (total === 0) {
            showingInfo.textContent = 'Showing 0 to 0 of 0 entries';
        } else {
            showingInfo.textContent = `Showing ${start} to ${end} of ${total} entries`;
        }
    }
    
    // Render pagination buttons dynamically
    function renderPagination() {
        const totalPages = getTotalPages();
        paginationContainer.innerHTML = '';
        
        // Previous page button
        const prevBtn = createButton('chevron_left', currentPage === 1);
        prevBtn.addEventListener('click', () => goToPage(currentPage - 1));
        paginationContainer.appendChild(prevBtn);
        
        // First page button
        const firstBtn = createButton('keyboard_double_arrow_left', currentPage === 1);
        firstBtn.addEventListener('click', () => goToPage(1));
        paginationContainer.appendChild(firstBtn);
        
        // Page number buttons with smart logic
        const pageButtons = getPageNumbers(currentPage, totalPages);
        pageButtons.forEach(item => {
            if (item === '...') {
                const dots = document.createElement('span');
                dots.className = 'pagination-dots';
                dots.textContent = '...';
                paginationContainer.appendChild(dots);
            } else {
                const btn = createButton(item, false, item === currentPage);
                btn.addEventListener('click', () => goToPage(item));
                paginationContainer.appendChild(btn);
            }
        });
        
        // Last page button
        const lastBtn = createButton('keyboard_double_arrow_right', currentPage === totalPages);
        lastBtn.addEventListener('click', () => goToPage(totalPages));
        paginationContainer.appendChild(lastBtn);
        
        // Next page button
        const nextBtn = createButton('chevron_right', currentPage === totalPages);
        nextBtn.addEventListener('click', () => goToPage(currentPage + 1));
        paginationContainer.appendChild(nextBtn);
    }
    
    // Create pagination button
    function createButton(content, disabled = false, active = false) {
        const btn = document.createElement('button');
        btn.className = 'pagination-btn';
        
        if (disabled) btn.disabled = true;
        if (active) btn.classList.add('active');
        
        if (['chevron_left', 'chevron_right', 'keyboard_double_arrow_left', 'keyboard_double_arrow_right'].includes(content)) {
            const icon = document.createElement('span');
            icon.className = 'material-symbols-outlined';
            icon.textContent = content;
            btn.appendChild(icon);
        } else {
            btn.textContent = content;
        }
        
        return btn;
    }
    
    // Get page numbers to display with smart logic
    function getPageNumbers(current, total) {
        const pages = [];
        
        if (total <= 5) {
            // If total pages <= 5, show all pages
            for (let i = 1; i <= total; i++) {
                pages.push(i);
            }
        } else {
            // Always show first page
            pages.push(1);
            
            // Determine which pages to show
            if (current <= 3) {
                // Near the beginning: 1 2 3 ... last
                pages.push(2);
                pages.push(3);
                pages.push('...');
                pages.push(total);
            } else if (current >= total - 2) {
                // Near the end: 1 ... last-2 last-1 last
                pages.push('...');
                pages.push(total - 2);
                pages.push(total - 1);
                pages.push(total);
            } else {
                // In the middle: 1 ... current-1 current current+1 ... last
                pages.push('...');
                pages.push(current - 1);
                pages.push(current);
                pages.push(current + 1);
                pages.push('...');
                pages.push(total);
            }
        }
        
        return pages;
    }
    
    // Go to specific page
    function goToPage(page) {
        const totalPages = getTotalPages();
        if (page < 1 || page > totalPages) return;
        
        currentPage = page;
        displayPage(currentPage);
        renderPagination();
    }
    
    // Initialize
    displayPage(currentPage);
    renderPagination();
});
</script>
@endpush
